name: Feature request
description: Suggest a change to C++Ay.
body:
  - type: textarea
    id: problem
    attributes:
      label: What would this help you do?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior
    validations:
      required: true
