# Linux -> Windows x86-64. Override these cache paths for a system SDK.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(AYPLAYER_MINGW_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.deps/mingw13/usr" CACHE PATH "MinGW Linux cross-toolchain prefix")
set(AYPLAYER_WINDOWS_QT "${CMAKE_CURRENT_LIST_DIR}/../../.deps/qt-windows" CACHE PATH "Windows MinGW Qt SDK prefix")
if(DEFINED ENV{QT_HOST_PATH} AND NOT "$ENV{QT_HOST_PATH}" STREQUAL "")
 set(_cppay_qt_host_default "$ENV{QT_HOST_PATH}")
else()
 set(_cppay_qt_host_default "/usr")
endif()
set(QT_HOST_PATH "${_cppay_qt_host_default}" CACHE PATH "Native Linux Qt SDK (same version as Windows Qt)")
get_filename_component(AYPLAYER_MINGW_ROOT "${AYPLAYER_MINGW_ROOT}" ABSOLUTE)
get_filename_component(AYPLAYER_WINDOWS_QT "${AYPLAYER_WINDOWS_QT}" ABSOLUTE)
set(CMAKE_CXX_COMPILER "${AYPLAYER_MINGW_ROOT}/bin/x86_64-w64-mingw32-g++")
set(CMAKE_RC_COMPILER "${AYPLAYER_MINGW_ROOT}/bin/x86_64-w64-mingw32-windres")
set(CMAKE_FIND_ROOT_PATH "${AYPLAYER_MINGW_ROOT}/x86_64-w64-mingw32" "${AYPLAYER_WINDOWS_QT}")
list(PREPEND CMAKE_PREFIX_PATH "${AYPLAYER_WINDOWS_QT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
